// Generated by tools/generate_board_descriptors.py. Do not edit.
import Foundation

public enum GeneratedBoardCatalog {
    public struct Expected: Sendable {
        public let chip: String
        public let profiles: [String]
        public let flashBytes: [Int]
        public let partition: String
        public let bootloaderAddress: Int
    }

    public static let sourceSHA256 = "af3ee2de5a4a5c4f6da6a33bbab8cec039f2a576894e73bb5faca9f7eae87fa4"
    public static let requiredFamilies: Set<String> = ["c6", "s3", "p4"]
    public static let expected: [String: Expected] = [
        "c6": Expected(chip: "esp32c6", profiles: ["st7789", "jd9853"], flashBytes: [8388608], partition: "default-8m", bootloaderAddress: 0),
        "s3": Expected(chip: "esp32s3", profiles: ["gc9107", "st7789-130", "st7789-154", "co5300", "st77916"], flashBytes: [8388608, 16777216, 33554432], partition: "universal-8m-doom-ota", bootloaderAddress: 0),
        "p4": Expected(chip: "esp32p4", profiles: ["st7703-4b"], flashBytes: [33554432], partition: "p4-32m-ota", bootloaderAddress: 8192),
    ]

    public static let profilesByTarget: [String: Set<String>] = [
        "c6": Set(["st7789", "jd9853"]),
        "s3": Set(["gc9107", "st7789-130", "st7789-154", "co5300", "st77916"]),
        "p4": Set(["st7703-4b"]),
        "p4-4b": Set(["st7703-4b"]),
        "s3-085": Set(["gc9107"]),
        "s3-154": Set(["st7789-154"]),
        "s3-175": Set(["co5300"]),
        "s3-185": Set(["st77916"]),
    ]

    public static let universalFamilyAliases: [String: Set<String>] = [
        "c6": Set(["c6"]),
        "s3": Set(["s3", "s3-085", "s3-154", "s3-175", "s3-185"]),
        "p4": Set(["p4", "p4-4b"]),
    ]

    public static let quarterTurnProfiles: Set<String> = Set(["st7703-4b", "gc9107", "st7789-130", "st7789-154", "co5300", "st77916"])
}
