// Generated by tools/generate_board_descriptors.py. Do not edit.
#pragma once

using namespace boarddetectmodel;

static constexpr CandidateRule GENERATED_C3_CANDIDATES[] = {
    {9, CandidateMatch::Always, 255, 0, 0},
};
static constexpr FamilyDetectionPlan GENERATED_C3_DETECTION = {
    nullptr, 0, GENERATED_C3_CANDIDATES,
    sizeof(GENERATED_C3_CANDIDATES) / sizeof(GENERATED_C3_CANDIDATES[0]), ResolutionPolicy::ExactlyOne};

static constexpr I2cProbePlan GENERATED_C6_PROBES[] = {
    {0, 0, 18, 19, 100000, 8, 119, {0x00, 0x00, 0x00, 0x00}, 0, 20, 20, 100, ProbeRelease::OnSuccessNoAck},
};
static constexpr CandidateRule GENERATED_C6_CANDIDATES[] = {
    {2, CandidateMatch::I2cAnyAckOrStartFailure, 0, 0, 0},
    {1, CandidateMatch::I2cNoAck, 0, 0, 0},
};
static constexpr FamilyDetectionPlan GENERATED_C6_DETECTION = {
    GENERATED_C6_PROBES, 1, GENERATED_C6_CANDIDATES,
    sizeof(GENERATED_C6_CANDIDATES) / sizeof(GENERATED_C6_CANDIDATES[0]), ResolutionPolicy::FirstMatch};

static constexpr I2cProbePlan GENERATED_S3_PROBES[] = {
    {8388608, 0, 15, 14, 100000, 0, 0, {0x5A, 0x34, 0x6A, 0x6B}, 4, -1, 0, 0, ProbeRelease::Always},
    {8388608, 0, 11, 10, 100000, 0, 0, {0x15, 0x20, 0x00, 0x00}, 2, -1, 0, 0, ProbeRelease::Always},
    {8388608, 0, 42, 41, 100000, 0, 0, {0x15, 0x6A, 0x6B, 0x00}, 3, -1, 0, 0, ProbeRelease::Always},
    {8388608, 0, 47, 48, 100000, 0, 0, {0x6B, 0x00, 0x00, 0x00}, 1, -1, 0, 0, ProbeRelease::Always},
    {8388608, 0, 6, 7, 100000, 0, 0, {0x15, 0x00, 0x00, 0x00}, 1, 1, 20, 300, ProbeRelease::Always},
};
static constexpr CandidateRule GENERATED_S3_CANDIDATES[] = {
    {5, CandidateMatch::FlashRange, 255, 0, 8388608},
    {3, CandidateMatch::I2cAnyAck, 0, 8388608, 0},
    {4, CandidateMatch::I2cAnyAck, 1, 8388608, 0},
    {6, CandidateMatch::I2cAnyAck, 2, 8388608, 0},
    {8, CandidateMatch::I2cAnyAck, 3, 8388608, 0},
    {11, CandidateMatch::I2cAnyAck, 4, 8388608, 0},
};
static constexpr FamilyDetectionPlan GENERATED_S3_DETECTION = {
    GENERATED_S3_PROBES, 5, GENERATED_S3_CANDIDATES,
    sizeof(GENERATED_S3_CANDIDATES) / sizeof(GENERATED_S3_CANDIDATES[0]), ResolutionPolicy::ExactlyOne};

static constexpr CandidateRule GENERATED_P4_CANDIDATES[] = {
    {7, CandidateMatch::Always, 255, 0, 0},
};
static constexpr FamilyDetectionPlan GENERATED_P4_DETECTION = {
    nullptr, 0, GENERATED_P4_CANDIDATES,
    sizeof(GENERATED_P4_CANDIDATES) / sizeof(GENERATED_P4_CANDIDATES[0]), ResolutionPolicy::FirstMatch};

static constexpr uint8_t GENERATED_MAX_PROBE_COUNT = 5;

inline const FamilyDetectionPlan &detectionPlanForPlatform(
    Platform platform) {
  switch (platform) {
    case Platform::Esp32C3: return GENERATED_C3_DETECTION;
    case Platform::Esp32C6: return GENERATED_C6_DETECTION;
    case Platform::Esp32S3: return GENERATED_S3_DETECTION;
    default: return GENERATED_P4_DETECTION;
  }
}
