// Generated by tools/generate_board_descriptors.py. Do not edit.
#pragma once

static constexpr AudioConfig GENERATED_BOARD_AUDIO[] = {
    {Variant::LcdSt7789, AudioAmp::None, AudioCodec::None, AudioMic::None, AudioSpeakerBus::None, AudioMicBus::None, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0, 0, 0, 0, 0, 0},
    {Variant::TouchJd9853, AudioAmp::None, AudioCodec::None, AudioMic::None, AudioSpeakerBus::None, AudioMicBus::None, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0, 0, 0, 0, 0, 0},
    {Variant::AmoledCo5300, AudioAmp::Ns4150b, AudioCodec::Es8311, AudioMic::Es7210, AudioSpeakerBus::I2s, AudioMicBus::I2s, 16, 9, 45, 8, 16, 9, 45, 10, -1, 46, 24, 64, 16000, 2, 16000, 2},
    {Variant::LcdSt77916, AudioAmp::Ns4150b, AudioCodec::Es8311, AudioMic::Es7210, AudioSpeakerBus::I2s, AudioMicBus::I2s, 2, 48, 38, 47, 2, 48, 38, 39, -1, 15, 24, 64, 16000, 2, 16000, 2},
    {Variant::LcdGc9107, AudioAmp::None, AudioCodec::None, AudioMic::None, AudioSpeakerBus::None, AudioMicBus::None, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0, 0, 0, 0, 0, 0},
    {Variant::TouchSt7789, AudioAmp::None, AudioCodec::None, AudioMic::None, AudioSpeakerBus::None, AudioMicBus::None, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0, 0, 0, 0, 0, 0},
    {Variant::P4_4B, AudioAmp::None, AudioCodec::None, AudioMic::None, AudioSpeakerBus::None, AudioMicBus::None, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0, 0, 0, 0, 0, 0},
    {Variant::LcdSt7789_130, AudioAmp::None, AudioCodec::None, AudioMic::None, AudioSpeakerBus::None, AudioMicBus::None, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0, 0, 0, 0, 0, 0},
    {Variant::C3_2424S012, AudioAmp::None, AudioCodec::None, AudioMic::None, AudioSpeakerBus::None, AudioMicBus::None, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0, 0, 0, 0, 0, 0},
    {Variant::LcdSt7789_190, AudioAmp::None, AudioCodec::None, AudioMic::None, AudioSpeakerBus::None, AudioMicBus::None, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0, 0, 0, 0, 0, 0},
    {Variant::ElecrowKnob128, AudioAmp::None, AudioCodec::None, AudioMic::None, AudioSpeakerBus::None, AudioMicBus::None, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0, 0, 0, 0, 0, 0},
};

inline const AudioConfig *generatedAudioConfig(Variant variant) {
  for (const auto &audio : GENERATED_BOARD_AUDIO) {
    if (audio.variant == variant) return &audio;
  }
  return nullptr;
}
