// Generated by tools/generate_board_descriptors.py. Do not edit.
#pragma once

enum class Variant : uint8_t {
  Unknown = 0,
  LcdSt7789 = 1,
  TouchJd9853 = 2,
  AmoledCo5300 = 3,
  LcdSt77916 = 4,
  LcdGc9107 = 5,
  TouchSt7789 = 6,
  P4_4B = 7,
  LcdSt7789_130 = 8,
};

constexpr bool supportsDoom(Variant variant) {
  return variant == Variant::AmoledCo5300 || variant == Variant::LcdSt77916 || variant == Variant::P4_4B;
}
