// Generated by tools/generate_board_descriptors.py. Do not edit.
#pragma once

inline const Config *generatedConfigFor(Variant variant) {
  switch (variant) {
    case Variant::LcdSt7789: return &CONFIG_LCD_ST7789;
    case Variant::TouchJd9853: return &CONFIG_TOUCH_JD9853;
    case Variant::AmoledCo5300: return &CONFIG_AMOLED_CO5300;
    case Variant::LcdSt77916: return &CONFIG_LCD_ST77916;
    case Variant::LcdGc9107: return &CONFIG_LCD_GC9107;
    case Variant::TouchSt7789: return &CONFIG_TOUCH_ST7789;
    case Variant::P4_4B: return &CONFIG_P4_4B;
    case Variant::LcdSt7789_130: return &CONFIG_LCD_ST7789_130;
    case Variant::C3_2424S012: return &CONFIG_C3_2424S012;
    case Variant::LcdSt7789_190: return &CONFIG_LCD_ST7789_190;
    case Variant::ElecrowKnob128: return &CONFIG_ELECROW_KNOB_128;
    default: return nullptr;
  }
}
