// Unity build for the Doom engine on ESP32-S3.
// Compiles all engine + platform C source as one translation unit,
// eliminating linker archive issues with Arduino's library system.
// This file is the ONLY .c that needs to be compiled for the engine.
//
// Why: Arduino's library linker uses archive mode which strips "unused"
// symbols from .a files. Since the engine's internal symbols reference
// each other circularly (I_Error in stubs, DG_DrawFrame in platform,
// W_OpenFile in WAD access), archive linking fails. Unity build solves
// this by putting everything in one object file.

// Platform stubs and bridge (order matters: stubs before engine)
#include "platform/doom_esp32_stubs.c.inc"
#include "platform/doomgeneric_esp32s3.c.inc"
#include "platform/w_file_esp32.c.inc"

// Network stub
#include "net_sdl.c.inc"

// Engine source (alphabetical)
#include "am_map.c.inc"
#include "d_event.c.inc"
#include "d_items.c.inc"
#include "d_iwad.c.inc"
#include "d_loop.c.inc"
#include "d_main.c.inc"
#include "d_mode.c.inc"
#include "d_net.c.inc"
#include "doomdef.c.inc"
#include "doomgeneric.c.inc"
#include "doomstat.c.inc"
#include "dstrings.c.inc"
#include "dummy.c.inc"
#include "f_finale.c.inc"
#include "f_wipe.c.inc"
#include "g_game.c.inc"
#include "gusconf.c.inc"
#include "hu_lib.c.inc"
#include "hu_stuff.c.inc"
#include "i_cdmus.c.inc"
#include "i_endoom.c.inc"
#include "i_input.c.inc"
#include "i_joystick.c.inc"
#include "i_scale.c.inc"
#include "i_sound.c.inc"
#include "i_system.c.inc"
#include "i_timer.c.inc"
#include "i_video.c.inc"
#include "info.c.inc"
#include "m_argv.c.inc"
#include "m_bbox.c.inc"
#include "m_cheat.c.inc"
#include "m_config.c.inc"
#include "m_controls.c.inc"
#include "m_fixed.c.inc"
#include "m_menu.c.inc"
#include "m_misc.c.inc"
#include "m_random.c.inc"
#include "memio.c.inc"
#include "mus2mid.c.inc"
#include "p_ceilng.c.inc"
#include "p_doors.c.inc"
#include "p_enemy.c.inc"
#include "p_floor.c.inc"
#include "p_inter.c.inc"
#include "p_lights.c.inc"
#include "p_map.c.inc"
#include "p_maputl.c.inc"
#include "p_mobj.c.inc"
#include "p_plats.c.inc"
#include "p_pspr.c.inc"
#include "p_saveg.c.inc"
#include "p_setup.c.inc"
#include "p_sight.c.inc"
#include "p_spec.c.inc"
#include "p_switch.c.inc"
#include "p_telept.c.inc"
#include "p_tick.c.inc"
#include "p_user.c.inc"
#include "r_bsp.c.inc"
#include "r_data.c.inc"
#include "r_draw.c.inc"
#include "r_main.c.inc"
#include "r_plane.c.inc"
#include "r_segs.c.inc"
#include "r_sky.c.inc"
#include "r_things.c.inc"
#include "s_sound.c.inc"
#include "sha1.c.inc"
#include "sounds.c.inc"
#include "st_lib.c.inc"
#include "st_stuff.c.inc"
#include "statdump.c.inc"
#include "tables.c.inc"
#include "v_video.c.inc"
#include "w_checksum.c.inc"
#include "w_main.c.inc"
#include "w_wad.c.inc"
#include "wi_stuff.c.inc"
#include "z_zone.c.inc"
