#!/usr/bin/env python3
"""Generate firmware, Python, and Swift board catalogs from boards/*.toml."""

from __future__ import annotations

import argparse
import os
import pathlib
import sys
from typing import Any, Dict, Iterable, List, Sequence, Tuple

import board_descriptor
from board_descriptor import detection_sense


HEADER = "// Generated by tools/generate_board_descriptors.py. Do not edit.\n"

PLATFORM_SYMBOLS = {
    "c3": "PLATFORM_ESP32_C3",
    "c6": "PLATFORM_ESP32_C6",
    "s3": "PLATFORM_ESP32_S3",
    "p4": "PLATFORM_ESP32_P4",
}
PLATFORM_ENUMS = {
    "c3": "Platform::Esp32C3",
    "c6": "Platform::Esp32C6",
    "s3": "Platform::Esp32S3",
    "p4": "Platform::Esp32P4",
}
WIFI_ENUMS = {
    "native": "WifiTopology::Native",
    "hosted_coprocessor": "WifiTopology::HostedCoprocessor",
}
IDENTITY_ENUMS = {
    "wifi_station_mac": "IdentitySource::WifiStationMac",
    "efuse_base_mac": "IdentitySource::EfuseBaseMac",
}
SERIAL_ENUMS = {
    "native_usb_cdc": "SerialTransport::NativeUsbCdc",
    "uart_bridge": "SerialTransport::UartBridge",
}
PANEL_BUS_ENUMS = {
    "spi": "PanelBus::Spi",
    "qspi": "PanelBus::Qspi",
    "mipi_dsi": "PanelBus::MipiDsi",
}
TOUCH_ENUMS = {
    "none": "TouchController::None",
    "axs5106l": "TouchController::Axs5106l",
    "cst9217": "TouchController::Cst9217",
    "cst816": "TouchController::Cst816",
    "gt911": "TouchController::Gt911",
}
POWER_ENUMS = {
    "none": "PowerController::None",
    "axp2101": "PowerController::Axp2101",
    "battery_adc": "PowerController::BatteryAdc",
}
MOTION_ENUMS = {
    "none": "MotionController::None",
    "qmi8658": "MotionController::Qmi8658",
}
AUDIO_AMP_ENUMS = {
    "none": "AudioAmp::None",
    "unknown": "AudioAmp::Unknown",
    "ns4150b": "AudioAmp::Ns4150b",
    "ns8002": "AudioAmp::Ns8002",
}
AUDIO_CODEC_ENUMS = {
    "none": "AudioCodec::None",
    "unknown": "AudioCodec::Unknown",
    "es8311": "AudioCodec::Es8311",
    "pcm5101a": "AudioCodec::Pcm5101a",
}
AUDIO_MIC_ENUMS = {
    "none": "AudioMic::None",
    "unknown": "AudioMic::Unknown",
    "es7210": "AudioMic::Es7210",
    "ics43434": "AudioMic::Ics43434",
    "pdm": "AudioMic::Pdm",
}
AUDIO_SPEAKER_BUS_ENUMS = {
    "none": "AudioSpeakerBus::None",
    "unknown": "AudioSpeakerBus::Unknown",
    "i2s": "AudioSpeakerBus::I2s",
}
AUDIO_MIC_BUS_ENUMS = {
    "none": "AudioMicBus::None",
    "unknown": "AudioMicBus::Unknown",
    "i2s": "AudioMicBus::I2s",
    "pdm": "AudioMicBus::Pdm",
}
MATCH_ENUMS = {
    "always": "CandidateMatch::Always",
    "flash_range": "CandidateMatch::FlashRange",
    "i2c_any_ack": "CandidateMatch::I2cAnyAck",
    "i2c_no_ack": "CandidateMatch::I2cNoAck",
    "i2c_any_ack_or_start_failure":
        "CandidateMatch::I2cAnyAckOrStartFailure",
}
RESOLUTION_ENUMS = {
    "first_match": "ResolutionPolicy::FirstMatch",
    "exactly_one": "ResolutionPolicy::ExactlyOne",
}
RELEASE_ENUMS = {
    "never": "ProbeRelease::Never",
    "always": "ProbeRelease::Always",
    "on_success_no_ack": "ProbeRelease::OnSuccessNoAck",
}


def _bool(value: bool) -> str:
    return "true" if value else "false"


def _q(value: str) -> str:
    return '"%s"' % value.replace("\\", "\\\\").replace('"', '\\"')


def _tuple(values: Sequence[str]) -> str:
    if not values:
        return "()"
    if len(values) == 1:
        return "(%s,)" % repr(values[0])
    return repr(tuple(values))


def _swift_array(values: Iterable[str]) -> str:
    return "[" + ", ".join(_q(value) for value in values) + "]"


def render_platform_config(
    grouped: Dict[str, List[Dict[str, Any]]],
) -> str:
    lines = [HEADER, "#pragma once\n\n"]
    for target in ("c3", "c6", "s3", "p4"):
        descriptor = grouped[target][0]
        family = descriptor["family"]
        platform = descriptor["platform"]
        identity = descriptor["identity"]
        lines.append(
            "static constexpr PlatformConfig %s = {\n"
            "    Platform::%s, %s, %s, %s, %s,\n"
            "    %s, %s, %s};\n"
            % (
                PLATFORM_SYMBOLS[target],
                board_descriptor.PLATFORM_ENUM[target],
                _q(identity["chip"]),
                _q(identity["partition"]),
                _bool(platform["use_psram_frame_buffers"]),
                _bool(platform["use_raw_lwip_receive_task"]),
                WIFI_ENUMS[platform["wifi"]],
                IDENTITY_ENUMS[platform["identity_source"]],
                SERIAL_ENUMS[platform["serial"]],
            )
        )
    return "".join(lines)


def render_variants(descriptors: Sequence[Dict[str, Any]]) -> str:
    ordered = sorted(
        descriptors, key=lambda item: item["identity"]["variant_value"])
    lines = [
        HEADER,
        "#pragma once\n\n",
        "enum class Variant : uint8_t {\n",
        "  Unknown = 0,\n",
    ]
    for descriptor in ordered:
        identity = descriptor["identity"]
        lines.append(
            "  %s = %d,\n"
            % (identity["variant"], identity["variant_value"])
        )
    lines.append("};\n\n")
    doom = [
        "variant == Variant::%s" % item["identity"]["variant"]
        for item in ordered if item["capabilities"]["doom"]
    ]
    lines.append("constexpr bool supportsDoom(Variant variant) {\n")
    lines.append("  return %s;\n" % (" || ".join(doom) if doom else "false"))
    lines.append("}\n")
    audio = [
        "variant == Variant::%s" % item["identity"]["variant"]
        for item in ordered if item["capabilities"]["audio"]
    ]
    lines.append("\nconstexpr bool supportsAudio(Variant variant) {\n")
    lines.append("  return %s;\n" % (" || ".join(audio) if audio else "false"))
    lines.append("}\n")
    return "".join(lines)


def render_identity(descriptors: Sequence[Dict[str, Any]]) -> str:
    ordered = sorted(
        descriptors, key=lambda item: item["identity"]["variant_value"])
    lines = [
        HEADER,
        "#pragma once\n\n",
        "struct GeneratedBoardIdentity {\n",
        "  Variant variant;\n",
        "  Platform platform;\n",
        "  const char *target;\n",
        "  const char *chip;\n",
        "  const char *profile;\n",
        "  const char *partition;\n",
        "};\n\n",
        "static constexpr GeneratedBoardIdentity GENERATED_BOARD_IDENTITIES[] = {\n",
    ]
    for descriptor in ordered:
        identity = descriptor["identity"]
        lines.append(
            "    {Variant::%s, %s, %s, %s, %s, %s},\n"
            % (
                identity["variant"],
                PLATFORM_ENUMS[identity["target"]],
                _q(identity["target"]),
                _q(identity["chip"]),
                _q(identity["profile"]),
                _q(identity["partition"]),
            )
        )
    lines.extend([
        "};\n\n",
        "inline const GeneratedBoardIdentity *generatedIdentity(Variant variant) {\n",
        "  for (const auto &identity : GENERATED_BOARD_IDENTITIES) {\n",
        "    if (identity.variant == variant) return &identity;\n",
        "  }\n",
        "  return nullptr;\n",
        "}\n",
    ])
    return "".join(lines)


def render_audio(descriptors: Sequence[Dict[str, Any]]) -> str:
    ordered = sorted(
        descriptors, key=lambda item: item["identity"]["variant_value"])
    lines = [
        HEADER,
        "#pragma once\n\n",
        "static constexpr AudioConfig GENERATED_BOARD_AUDIO[] = {\n",
    ]
    for descriptor in ordered:
        identity = descriptor["identity"]
        audio = descriptor["audio"]
        lines.append(
            "    {Variant::%s, %s, %s, %s, %s, %s, "
            "%d, %d, %d, %d, %d, %d, %d, %d, %d, %d, "
            "%d, %d, %d, %d, %d, %d},\n"
            % (
                identity["variant"],
                AUDIO_AMP_ENUMS[audio["amp"]],
                AUDIO_CODEC_ENUMS[audio["codec"]],
                AUDIO_MIC_ENUMS[audio["mic"]],
                AUDIO_SPEAKER_BUS_ENUMS[audio["speaker_bus"]],
                AUDIO_MIC_BUS_ENUMS[audio["mic_bus"]],
                audio["pin_playback_mclk"],
                audio["pin_playback_bclk"],
                audio["pin_playback_lrck"],
                audio["pin_dout"],
                audio["pin_capture_mclk"],
                audio["pin_capture_bclk"],
                audio["pin_capture_lrck"],
                audio["pin_din"],
                audio["pin_pdm_clock"],
                audio["pin_amp_enable"],
                audio["codec_i2c_address"],
                audio["mic_i2c_address"],
                audio["playback_rate_hz"],
                audio["playback_channels"],
                audio["capture_rate_hz"],
                audio["capture_channels"],
            )
        )
    lines.extend([
        "};\n\n",
        "inline const AudioConfig *generatedAudioConfig(Variant variant) {\n",
        "  for (const auto &audio : GENERATED_BOARD_AUDIO) {\n",
        "    if (audio.variant == variant) return &audio;\n",
        "  }\n",
        "  return nullptr;\n",
        "}\n",
    ])
    return "".join(lines)


def _panel_initializer(descriptor: Dict[str, Any]) -> str:
    panel = descriptor["panel"]
    return (
        "static constexpr PanelConfig %(symbol)s = {\n"
        "    PanelProfile::%(profile)s, PanelDriver::%(driver)s, %(bus)s,\n"
        "    %(width)d, %(height)d, %(memory_width)d, %(memory_height)d,\n"
        "    %(pixel_clock_hz)d, %(spi_mode)d, "
        "%(col_offset)d, %(row_offset)d, %(orientation_offset)d,\n"
        "    %(invert)s, %(round)s, %(rotation)s,\n"
        "    %(dsi_data_lanes)d, %(dsi_lane_mbps)d, "
        "%(hsync_back_porch)d, %(hsync_pulse_width)d, "
        "%(hsync_front_porch)d,\n"
        "    %(vsync_back_porch)d, %(vsync_pulse_width)d, "
        "%(vsync_front_porch)d};\n"
        % {
            **panel,
            "bus": PANEL_BUS_ENUMS[panel["bus"]],
            "invert": _bool(panel["invert_color"]),
            "round": _bool(panel["round_display"]),
            "rotation": _bool(panel["supports_command_rotation"]),
        }
    )


def _config_initializer(descriptor: Dict[str, Any]) -> str:
    identity = descriptor["identity"]
    carrier = descriptor["carrier"]
    touch = descriptor["touch"]
    power = descriptor["power"]
    motion = descriptor["motion"]
    reset = descriptor["reset"]
    backlight = descriptor["backlight"]
    serial = descriptor["serial"]
    values = [
        "Variant::%s" % identity["variant"],
        _q(descriptor["name"]),
        "&%s" % PLATFORM_SYMBOLS[identity["target"]],
        "&%s" % descriptor["panel"]["symbol"],
        *(str(carrier[key]) for key in (
            "pin_sclk", "pin_mosi", "pin_data1", "pin_data2", "pin_data3",
            "pin_cs", "pin_dc", "pin_rst", "pin_bl", "pin_boot",
            "pin_rgb_led")),
        TOUCH_ENUMS[touch["controller"]],
        *(str(touch[key]) for key in ("sda", "scl", "reset", "interrupt")),
        POWER_ENUMS[power["controller"]],
        *(str(power[key]) for key in (
            "battery_adc", "battery_adc_scale", "battery_enable",
            "charge_status")),
        MOTION_ENUMS[motion["controller"]],
        str(motion["x_axis"]),
        str(motion["x_sign"]),
        str(motion["y_axis"]),
        str(motion["y_sign"]),
        str(reset["panel_output"]),
        str(reset["touch_output"]),
        str(backlight["enable_pin"]),
        _bool(backlight["inverted"]),
        str(serial["rx"]),
        str(serial["tx"]),
        *(str(board_descriptor.optional_pin(descriptor, "carrier." + key))
          for key in ("pin_panel_power", "pin_encoder_a", "pin_encoder_b")),
        _bool(descriptor["led"]["channel_order"] == "grb"),
    ]
    rendered = []
    for index in range(0, len(values), 6):
        rendered.append("    " + ", ".join(values[index:index + 6]) + ",\n")
    rendered[-1] = rendered[-1].rstrip(",\n") + "\n"
    return "static constexpr Config %s = {\n%s};\n" % (
        descriptor["migration"]["config_symbol"], "".join(rendered))


def render_configs(descriptors: Sequence[Dict[str, Any]]) -> str:
    generated = [
        descriptor for descriptor in descriptors
        if descriptor["migration"]["firmware_config"] == "generated"
    ]
    lines = [HEADER, "#pragma once\n\n"]
    emitted_panels = set()
    for descriptor in descriptors:
        # Carriers may share one panel profile; the validator has already
        # required every sharer to state identical panel facts.
        symbol = descriptor["panel"]["symbol"]
        if symbol in emitted_panels:
            continue
        emitted_panels.add(symbol)
        lines.append(_panel_initializer(descriptor))
    lines.append("\n")
    for descriptor in generated:
        lines.append(_config_initializer(descriptor))
    return "".join(lines)


def render_config_lookup(descriptors: Sequence[Dict[str, Any]]) -> str:
    ordered = sorted(
        descriptors, key=lambda item: item["identity"]["variant_value"])
    lines = [
        HEADER,
        "#pragma once\n\n",
        "inline const Config *generatedConfigFor(Variant variant) {\n",
        "  switch (variant) {\n",
    ]
    for descriptor in ordered:
        lines.append(
            "    case Variant::%s: return &%s;\n"
            % (
                descriptor["identity"]["variant"],
                descriptor["migration"]["config_symbol"],
            )
        )
    lines.extend([
        "    default: return nullptr;\n",
        "  }\n",
        "}\n",
    ])
    return "".join(lines)


def _physical_probe_key(descriptor: Dict[str, Any]) -> Tuple[Any, ...]:
    detection = descriptor["detection"]
    if detection["sda"] < 0:
        return ()
    return (
        detection["flash_min_exclusive"],
        detection["flash_max_inclusive"],
        detection["sda"],
        detection["scl"],
        detection["frequency_hz"],
        detection["scan_first"],
        detection["scan_last"],
        tuple(detection["addresses"]),
        detection["reset_pin"],
        detection["reset_low_ms"],
        detection["reset_release_wait_ms"],
        detection["release"],
    )


def render_detection(
    grouped: Dict[str, List[Dict[str, Any]]],
) -> str:
    max_probe_count = 0
    max_sense_count = 0
    lines = [
        HEADER,
        "#pragma once\n\n",
        "using namespace boarddetectmodel;\n\n",
    ]
    for target in ("c3", "c6", "s3", "p4"):
        family = sorted(
            grouped[target], key=lambda item: item["detection"]["order"])
        probes: List[Tuple[Any, ...]] = []
        for descriptor in family:
            key = _physical_probe_key(descriptor)
            if key and key not in probes:
                probes.append(key)
        max_probe_count = max(max_probe_count, len(probes))
        prefix = target.upper()
        if probes:
            lines.append(
                "static constexpr I2cProbePlan GENERATED_%s_PROBES[] = {\n"
                % prefix
            )
            for probe in probes:
                (
                    flash_min, flash_max, sda, scl, frequency, scan_first,
                    scan_last, addresses, reset_pin, reset_low, reset_wait,
                    release,
                ) = probe
                padded = list(addresses) + [0] * (4 - len(addresses))
                lines.append(
                    "    {%d, %d, %d, %d, %d, %d, %d, "
                    "{%s}, %d, %d, %d, %d, %s},\n"
                    % (
                        flash_min, flash_max, sda, scl, frequency,
                        scan_first, scan_last,
                        ", ".join("0x%02X" % value for value in padded),
                        len(addresses), reset_pin, reset_low, reset_wait,
                        RELEASE_ENUMS[release],
                    )
                )
            lines.append("};\n")
        sense_pins: List[int] = []
        for descriptor in family:
            pin = detection_sense(descriptor)[0]
            if pin >= 0 and pin not in sense_pins:
                sense_pins.append(pin)
        max_sense_count = max(max_sense_count, len(sense_pins))
        if sense_pins:
            lines.append(
                "static constexpr int8_t GENERATED_%s_SENSE_PINS[] = {%s};\n"
                % (prefix, ", ".join("%d" % pin for pin in sense_pins))
            )
        lines.append(
            "static constexpr CandidateRule GENERATED_%s_CANDIDATES[] = {\n"
            % prefix
        )
        for descriptor in family:
            detection = descriptor["detection"]
            probe_key = _physical_probe_key(descriptor)
            probe_index = probes.index(probe_key) if probe_key else 255
            sense_pin, sense_min, sense_max = detection_sense(descriptor)
            sense_suffix = ""
            if sense_pin >= 0:
                sense_suffix = ", %d, %d, %d" % (
                    sense_pins.index(sense_pin), sense_min, sense_max)
            lines.append(
                "    {%d, %s, %d, %d, %d%s},\n"
                % (
                    descriptor["identity"]["variant_value"],
                    MATCH_ENUMS[detection["kind"]],
                    probe_index,
                    detection["flash_min_exclusive"],
                    detection["flash_max_inclusive"],
                    sense_suffix,
                )
            )
        lines.append("};\n")
        resolution = RESOLUTION_ENUMS[family[0]["detection"]["resolution"]]
        probe_ref = "GENERATED_%s_PROBES" % prefix if probes else "nullptr"
        sense_ref = ""
        if sense_pins:
            sense_ref = ",\n    GENERATED_%s_SENSE_PINS, %d" % (
                prefix, len(sense_pins))
        lines.append(
            "static constexpr FamilyDetectionPlan GENERATED_%s_DETECTION = {\n"
            "    %s, %d, GENERATED_%s_CANDIDATES,\n"
            "    sizeof(GENERATED_%s_CANDIDATES) / "
            "sizeof(GENERATED_%s_CANDIDATES[0]), %s%s};\n\n"
            % (prefix, probe_ref, len(probes), prefix, prefix, prefix,
               resolution, sense_ref)
        )
    lines.append(
        "static constexpr uint8_t GENERATED_MAX_PROBE_COUNT = %d;\n"
        "static constexpr uint8_t GENERATED_MAX_SENSE_COUNT = %d;\n\n"
        % (max_probe_count, max_sense_count)
    )
    lines.extend([
        "inline const FamilyDetectionPlan &detectionPlanForPlatform(\n",
        "    Platform platform) {\n",
        "  switch (platform) {\n",
        "    case Platform::Esp32C3: return GENERATED_C3_DETECTION;\n",
        "    case Platform::Esp32C6: return GENERATED_C6_DETECTION;\n",
        "    case Platform::Esp32S3: return GENERATED_S3_DETECTION;\n",
        "    default: return GENERATED_P4_DETECTION;\n",
        "  }\n",
        "}\n",
    ])
    return "".join(lines)


def render_p4_compile(grouped: Dict[str, List[Dict[str, Any]]]) -> str:
    descriptor = next(
        item for item in grouped["p4"]
        if item["migration"]["firmware_config"] == "generated")
    selector = descriptor["compile"]["selector"]
    lines = [HEADER, "#pragma once\n\n", "#if defined(%s)\n" % selector]
    for macro in descriptor["compile"]["macros"]:
        lines.append("#define %s 1\n" % macro)
    lines.append(
        "static const Variant COMPILED_VARIANT = Variant::%s;\n"
        % descriptor["identity"]["variant"]
    )
    lines.append("#endif\n")
    return "".join(lines)


def render_python_catalog(
    grouped: Dict[str, List[Dict[str, Any]]], digest: str,
) -> str:
    lines = [
        "# Generated by tools/generate_board_descriptors.py. Do not edit.\n",
        "SOURCE_SHA256 = %r\n\n" % digest,
        "PLATFORMS = {\n",
    ]
    for target in ("c3", "c6", "s3", "p4"):
        descriptor = grouped[target][0]
        family = descriptor["family"]
        identity = descriptor["identity"]
        lines.append(
            "    %r: dict(key=%r, chip=%r, fqbn=%r, bootloader_address=%d),\n"
            % (
                target, family["platform_key"], identity["chip"],
                family["fqbn"], family["bootloader_address"],
            )
        )
    lines.append("}\n\nBUILD_TARGETS = {\n")
    for target in ("c3", "c6", "s3", "p4"):
        descriptor = grouped[target][0]
        family = descriptor["family"]
        generated = next(
            item for item in grouped[target]
            if item["migration"]["firmware_config"] == "generated")
        required_profile = (
            generated["identity"]["profile"]
            if target == "p4" else None
        )
        lines.append(
            "    %r: dict(key=%r, platform=%r, partition_csv=%r, "
            "extra_flags=%r, extra_library_dirs=%r, required_profile=%r, "
            "fqbn_options=%r),\n"
            % (
                family["build_target"], family["build_target"], target,
                family["partition_csv"] or None,
                tuple(family["extra_flags"]),
                tuple(family["extra_library_dirs"]),
                required_profile,
                tuple(family["fqbn_options"]),
            )
        )
    lines.append("}\n\nFAMILIES = {\n")
    for target in ("c3", "c6", "s3", "p4"):
        descriptor = grouped[target][0]
        family = descriptor["family"]
        profiles = tuple(item["identity"]["profile"] for item in grouped[target])
        hardware = {
            item["identity"]["profile"]: tuple(item["hardware"])
            for item in grouped[target]
        }
        lines.append(
            "    %r: dict(key=%r, platform=%r, build_target=%r, profiles=%r, "
            "flash_sizes=%r, partition_scheme=%r, requires_doom_wad=%r, "
            "hardware=%r, blurb=%r),\n"
            % (
                target, target, target, family["build_target"], profiles,
                tuple(family["flash_bytes"]),
                descriptor["identity"]["partition"],
                family["requires_doom_wad"], hardware, family["blurb"],
            )
        )
    lines.append("}\n\nLEGACY_TARGET_PROFILES = {\n")
    for family in grouped.values():
        for descriptor in family:
            for legacy in descriptor["identity"]["legacy_targets"]:
                lines.append(
                    "    %r: %r,\n"
                    % (legacy, descriptor["identity"]["profile"])
                )
    lines.append("}\n")
    return "".join(lines)


def render_swift_catalog(
    grouped: Dict[str, List[Dict[str, Any]]], digest: str,
) -> str:
    lines = [
        HEADER,
        "import Foundation\n\n",
        "public enum GeneratedBoardCatalog {\n",
        "    public struct Expected: Sendable {\n",
        "        public let chip: String\n",
        "        public let profiles: [String]\n",
        "        public let flashBytes: [Int]\n",
        "        public let partition: String\n",
        "        public let bootloaderAddress: Int\n",
        "    }\n\n",
        "    public static let sourceSHA256 = %s\n" % _q(digest),
        "    public static let requiredFamilies: Set<String> = "
        + _swift_array(("c3", "c6", "s3", "p4")) + "\n",
        "    public static let expected: [String: Expected] = [\n",
    ]
    for target in ("c3", "c6", "s3", "p4"):
        descriptor = grouped[target][0]
        family = descriptor["family"]
        profiles = [
            item["identity"]["profile"] for item in grouped[target]
        ]
        lines.append(
            "        %s: Expected(chip: %s, profiles: %s, flashBytes: %s, "
            "partition: %s, bootloaderAddress: %d),\n"
            % (
                _q(target), _q(descriptor["identity"]["chip"]),
                _swift_array(profiles), repr(family["flash_bytes"]),
                _q(descriptor["identity"]["partition"]),
                family["bootloader_address"],
            )
        )
    lines.append("    ]\n\n")
    lines.append("    public static let profilesByTarget: [String: Set<String>] = [\n")
    for target in ("c3", "c6", "s3", "p4"):
        profiles = [
            item["identity"]["profile"] for item in grouped[target]
        ]
        lines.append(
            "        %s: Set(%s),\n" % (_q(target), _swift_array(profiles))
        )
    for family in grouped.values():
        for descriptor in family:
            for legacy in descriptor["identity"]["legacy_targets"]:
                lines.append(
                    "        %s: Set([%s]),\n"
                    % (_q(legacy), _q(descriptor["identity"]["profile"]))
                )
    lines.append("    ]\n\n")
    lines.append("    public static let geometryByProfile: [String: PanelGeometry] = [\n")
    for target in ("c3", "c6", "s3", "p4"):
        for descriptor in grouped[target]:
            profile = descriptor["identity"]["profile"]
            panel = descriptor["panel"]
            lines.append(
                "        %s: PanelGeometry(width: %d, height: %d),\n"
                % (_q(profile), panel["width"], panel["height"])
            )
    lines.append("    ]\n\n")
    lines.append("    public static let universalFamilyAliases: [String: Set<String>] = [\n")
    for target in ("c3", "c6", "s3", "p4"):
        aliases = {target}
        for descriptor in grouped[target]:
            aliases.update(descriptor["identity"]["legacy_targets"])
        lines.append(
            "        %s: Set(%s),\n"
            % (_q(target), _swift_array(sorted(aliases)))
        )
    lines.append("    ]\n\n")
    quarter_turns = [
        descriptor["identity"]["profile"]
        for family in grouped.values()
        for descriptor in family
        if 1 in descriptor["orientation"]["quarter_turns"]
    ]
    lines.append(
        "    public static let quarterTurnProfiles: Set<String> = Set(%s)\n"
        % _swift_array(quarter_turns)
    )
    lines.append("}\n")
    return "".join(lines)


def expected_outputs(repo_root: str) -> Dict[str, str]:
    descriptors = list(board_descriptor.validate_descriptors(
        board_descriptor.load_repository_descriptors(repo_root)))
    grouped = board_descriptor.grouped_by_family(descriptors)
    required_families = {"c3", "c6", "s3", "p4"}
    if set(grouped) != required_families:
        raise board_descriptor.DescriptorError(
            "descriptor repository must contain exactly c3, c6, s3, and p4; found %s"
            % ", ".join(sorted(grouped))
        )
    digest = board_descriptor.descriptor_source_digest(repo_root)
    return {
        "firmware/libraries/espdisp_board/src/generated_platform_config.h":
            render_platform_config(grouped),
        "firmware/libraries/espdisp_board/src/generated_board_variants.h":
            render_variants(descriptors),
        "firmware/libraries/espdisp_board/src/generated_board_identity.h":
            render_identity(descriptors),
        "firmware/libraries/espdisp_board/src/generated_board_audio.h":
            render_audio(descriptors),
        "firmware/libraries/espdisp_board/src/generated_board_configs.h":
            render_configs(descriptors),
        "firmware/libraries/espdisp_board/src/generated_board_config_lookup.h":
            render_config_lookup(descriptors),
        "firmware/libraries/espdisp_board/src/generated_board_detection.h":
            render_detection(grouped),
        "firmware/libraries/espdisp_board/src/generated_p4_compile.h":
            render_p4_compile(grouped),
        "tools/generated_board_catalog.py":
            render_python_catalog(grouped, digest),
        "mac/ESPDisplaySender/Sources/SenderProtocol/GeneratedBoardCatalog.swift":
            render_swift_catalog(grouped, digest),
    }


def write_outputs(repo_root: str, check: bool) -> bool:
    stale = []
    for relative, content in expected_outputs(repo_root).items():
        path = pathlib.Path(repo_root) / relative
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == content:
            continue
        stale.append(relative)
        if not check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    if stale and check:
        print(
            "generated board files are stale: %s; run "
            "python3 tools/generate_board_descriptors.py"
            % ", ".join(stale),
            file=sys.stderr,
        )
        return False
    if not check:
        for relative in stale:
            print("generated %s" % relative)
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    try:
        return 0 if write_outputs(repo_root, args.check) else 1
    except board_descriptor.DescriptorError as exc:
        print("board descriptor error: %s" % exc, file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
