# Generated by tools/generate_board_descriptors.py. Do not edit.
SOURCE_SHA256 = '74df6a5c24abc9f1dc72fbebfef27368c43274d99be6f1c14c83e9df9c419c4b'

PLATFORMS = {
    'c6': dict(key='c6', chip='esp32c6', fqbn='esp32:esp32:esp32c6:CDCOnBoot=cdc,FlashSize=8M', bootloader_address=0),
    's3': dict(key='s3', chip='esp32s3', fqbn='esp32:esp32:esp32s3:CDCOnBoot=cdc,FlashSize=8M,PSRAM=opi,PartitionScheme=custom', bootloader_address=0),
    'p4': dict(key='p4', chip='esp32p4', fqbn='esp32:esp32:esp32p4:USBMode=default,CDCOnBoot=default,UploadMode=default,FlashSize=32M,PartitionScheme=custom,PSRAM=enabled,ChipVariant=prev3', bootloader_address=8192),
}

BUILD_TARGETS = {
    'c6': dict(key='c6', platform='c6', partition_csv=None, extra_flags=(), extra_library_dirs=(), required_profile=None, fqbn_options=()),
    's3-universal': dict(key='s3-universal', platform='s3', partition_csv='partitions_s3.csv', extra_flags=('-DESPDISP_DOOM_RUNTIME',), extra_library_dirs=('firmware',), required_profile=None, fqbn_options=()),
    'p4-4b': dict(key='p4-4b', platform='p4', partition_csv='partitions_p4_4b.csv', extra_flags=('-DESPDISP_BOARD_P4_4B', '-DESPDISP_DOOM_RUNTIME'), extra_library_dirs=('firmware',), required_profile='st7703-4b', fqbn_options=('UploadSpeed=460800',)),
}

FAMILIES = {
    'c6': dict(key='c6', platform='c6', build_target='c6', profiles=('st7789', 'jd9853'), flash_sizes=(8388608,), partition_scheme='default-8m', requires_doom_wad=False, hardware={'st7789': ('ESP32-C6-LCD-1.47',), 'jd9853': ('ESP32-C6-Touch-LCD-1.47',)}, blurb='Universal ESP32-C6 1.47" display firmware'),
    's3': dict(key='s3', platform='s3', build_target='s3-universal', profiles=('gc9107', 'st7789-130', 'st7789-154', 'co5300', 'st77916'), flash_sizes=(8388608, 16777216, 33554432), partition_scheme='universal-8m-doom-ota', requires_doom_wad=True, hardware={'gc9107': ('ESP32-S3-LCD-0.85',), 'st7789-130': ('ESP32-S3-LCD-1.3', 'ESP32-S3-LCD-1.3-B', 'ESP32-S3-LCD-1.3-C'), 'st7789-154': ('ESP32-S3-Touch-LCD-1.54',), 'co5300': ('ESP32-S3-Touch-AMOLED-1.75C',), 'st77916': ('ESP32-S3-Touch-LCD-1.85C',)}, blurb='Universal ESP32-S3 display firmware'),
    'p4': dict(key='p4', platform='p4', build_target='p4-4b', profiles=('st7703-4b',), flash_sizes=(33554432,), partition_scheme='p4-32m-ota', requires_doom_wad=True, hardware={'st7703-4b': ('ESP32-P4-WIFI6-Touch-LCD-4B',)}, blurb='Universal ESP32-P4 display firmware'),
}

LEGACY_TARGET_PROFILES = {
    'p4-4b': 'st7703-4b',
    's3-085': 'gc9107',
    's3-154': 'st7789-154',
    's3-175': 'co5300',
    's3-185': 'st77916',
}
